- name: Check if hub is installed
  stat:
    path: /usr/local/bin/hub
  register: hub_stat

- name: Download hub
  unarchive:
    remote_src: true
    src: "https://github.com/github/hub/releases/download/v{{ hub_linux_version }}/{{ hub_linux_full_version }}.tgz"
    dest: /tmp/
  when: not hub_stat.stat.exists

- name: Install hub
  command: "bash -x /tmp/{{ hub_linux_full_version }}/install"
  become: true
  register: hub_output
  when: not hub_stat.stat.exists
- debug: var=hub_output

- name: Clean hub files
  command: rm -rf /tmp/{{ hub_linux_full_version }}{,.tgz}
