colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: vim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default:
    encrypt: true
    journal: ~/Dropbox/.journal.txt
  til:
    encrypt: false
    journal: ~/Dropbox/.til.txt
  work:
    encrypt: true
    journal: ~/Dropbox/.work.txt
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v4.2
