# NOTE: if this is false, you'll need to run :PluginInstall in vim to
# install all plugins
vim_install_plugins: no

# Only used on OSX machines. Ignored on other platforms
vim_install_macvim: yes

# Only install a minimal subset of the full vimrc (e.g. for remote servers)
vim_minimal: no
