---
- name: Make sure zsh is installed
  ansible.builtin.homebrew: name=zsh state=present

# Configuration
- name: Check if zshrc already exists
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

# Ensure the dotfiles repository gets cloned in remote hosts, like my mac mini, but not on localhost
- name: Clone dotfiles repository
  git:
    repo: https://github.com/sloria/dotfiles.git
    dest: "{{ dotfiles_user_home }}/dotfiles"
    clone: yes
  when: inventory_hostname != 'localhost'

- import_tasks: prezto.yml
  when: zsh_prezto

- name: Copy minimal zshrc
  copy: src=zshrc_minimal dest={{dotfiles_user_home}}/.zshrc
  when: not zsh_prezto
