
# Installation and setup
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: redhat.yml
  when: ansible_os_family == "RedHat"
- include: osx.yml
  when: ansible_os_family == "Darwin"

# Configuration
- name: Check if zshrc already exists
  stat: path="{{'~/.zshrc' | expanduser }}"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{ '~/.zshrc.bak' | expanduser}}"
  when: zshrc_stat.stat.exists

- include: prezto.yml
  when: zsh_prezto

- name: Copy minimal zshrc
  copy: src=zshrc_minimal dest={{dotfiles_user_home}}/.zshrc
  when: not zsh_prezto
