
- include: osx.yml
  when: ansible_os_family == "Darwin"
- include: debian.yml
  when: ansible_os_family == "Debian"

# TODO: Fedora

- name: Install tmuxp
  pip: name=tmuxp state=latest
  when: tmux_install_tmuxp

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{dotfiles_user_home}}/.tmux/plugins/tpm"

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{dotfiles_user_home}}/.tmux.conf"
    state: link
  when: ansible_os_family != "Darwin"

# On OSX, use the same tmux.conf, but also use
# reattach_to_user_namespace (for clipboard support)
- name: Symlink .tmux.conf (OSX)
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux-osx.conf"
    dest: "{{dotfiles_user_home}}/.tmux.conf"
    state: link
  when: ansible_os_family == "Darwin"
