
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

# TODO: Fedora

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{dotfiles_user_home}}/.tmux/plugins/tpm"

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{dotfiles_user_home}}/.tmux.conf"
    state: link
  when: ansible_os_family != "Darwin"

# On macOS, use the same tmux.conf, but also use
# reattach_to_user_namespace (for clipboard support)
- name: Symlink .tmux.conf (macOS)
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux-mac.conf"
    dest: "{{dotfiles_user_home}}/.tmux.conf"
    state: link
  when: ansible_os_family == "Darwin"
