- name: Install Mac Vim
  homebrew: name=macvim state=present
  when: vim_install_macvim|bool

- name: Install exuberant-ctags (needed for TagBar plugin)
  homebrew: name=ctags-exuberant state=present
