# NOTE: The with-override-system-vim option ensures that you have an up-to-date terminal vim
- name: Install Mac Vim
  homebrew: name=macvim state=present install_options=with-python3,with-lua,with-luajit,with-override-system-vim
  when: vim_install_macvim

- name: Install exuberant-ctags (needed for TagBar plugin)
  homebrew: name=ctags-exuberant state=present
